SET search_path TO gs_gss, public;

DO $$
BEGIN
    -- 新 schema 已有 build_number 欄位，代表 migration 已完成，略過
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'gs_gss'
          AND table_name = 'gs_version'
          AND column_name = 'build_number'
    ) THEN
        RETURN;
    END IF;

    -- 1. 建新表
    CREATE TABLE gs_version_new (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        db_version      VARCHAR(64),
        build_number    VARCHAR(64) NOT NULL,
        description     TEXT,
        created_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        version         INTEGER NOT NULL DEFAULT 0,
        CONSTRAINT uq_gs_version_build_number UNIQUE (build_number)
    );

    -- 2. 搬資料（依你實際 build_number 規則調整）
    INSERT INTO gs_version_new (db_version, build_number, description, created_time, updated_time)
    SELECT
        version,
        version,
        description,
        COALESCE(applied_at, created_time, NOW()),
        COALESCE(updated_time, applied_at, NOW())
    FROM gs_version;

    -- 3. 換表
    DROP TABLE gs_version;
    ALTER TABLE gs_version_new RENAME TO gs_version;

    -- 4. reset id
    PERFORM setval(
        pg_get_serial_sequence('gs_version', 'id'),
        (SELECT COALESCE(MAX(id), 1) FROM gs_version)
    );
END $$;
