SET search_path TO gs_gss, public;

-- 1. 建新表
CREATE TABLE gs_version_new (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    db_version      VARCHAR(64),
    build_number    VARCHAR(64) NOT NULL,
    description     TEXT,
    created_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_gs_version_build_number UNIQUE (build_number)
);

-- 2. 搬資料（依你實際 build_number 規則調整）
INSERT INTO gs_version_new (db_version, build_number, description, created_time, updated_time)
SELECT
    version,                          -- 舊 version → db_version
    version,                          -- 或改成 'v1.0.0-TP-0000' 這類 build 號
    description,
    COALESCE(applied_at, created_time, NOW()),
    COALESCE(updated_time, applied_at, NOW())
FROM gs_version;

-- 3. 換表
DROP TABLE gs_version;
ALTER TABLE gs_version_new RENAME TO gs_version;

-- 4.reset id
SELECT setval(pg_get_serial_sequence('gs_version', 'id'), (SELECT COALESCE(MAX(id), 1) FROM gs_version));