-- TCG-166594: audit trail when GME catalog sync overwrites games.supports_* flags
-- 記錄 games.supports_freegame / supports_bonusgame 每次實際變更；應用層在條件式更新成功時同步寫入一筆。
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS game_supports_history (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主鍵
    game_id                     BIGINT      NOT NULL, -- FK → games(id)；哪個遊戲
    previous_supports_freegame  BOOLEAN     NOT NULL, -- 變更前是否支援購買 Freegame
    supports_freegame           BOOLEAN     NOT NULL, -- 變更後是否支援購買 Freegame
    previous_supports_bonusgame BOOLEAN     NOT NULL, -- 變更前是否支援購買 Bonusgame
    supports_bonusgame          BOOLEAN     NOT NULL, -- 變更後是否支援購買 Bonusgame
    source                      VARCHAR(64) NOT NULL, -- 觸發來源（如 GME_CATALOG_SYNC）
    sync_run_id                 UUID        NOT NULL, -- 同一次同步 run 的識別，用於串連同批變更
    created_time                TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- 事件時間
    updated_time                TIMESTAMPTZ,                       -- 最後更新時間；與專案其他表一致
    version                     INTEGER     NOT NULL DEFAULT 0 -- 與專案其他表一致
);

-- 依遊戲 + 時間倒序（列表／排查常用）
CREATE INDEX IF NOT EXISTS idx_gsh_gi_ct ON game_supports_history (game_id, created_time DESC);

COMMENT ON TABLE game_supports_history IS
    'GME catalog sync purchase-support flag changes (TCG-166594); one row per game per sync update';
