-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE action_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    platform_id    BIGINT, -- 邏輯 FK → platforms(id)；方便列表依平台過濾
    menu_code      VARCHAR(100), -- 稽核快照，對應 menus.code（原 menu_slug）
    menu_path      TEXT,
    action         VARCHAR(50),
    request_method VARCHAR(10),
    request_url    TEXT,
    request_ip     VARCHAR(45),
    content        JSONB,
    created_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time   TIMESTAMPTZ,
    version        INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX action_logs_user_id_idx         ON action_logs (user_id);
CREATE INDEX action_logs_platform_id_idx     ON action_logs (platform_id);
CREATE INDEX action_logs_created_time_idx    ON action_logs (created_time DESC);
CREATE INDEX action_logs_menu_code_idx       ON action_logs (menu_code);
CREATE INDEX action_logs_content_gin_idx ON action_logs USING GIN (content);
