-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_action_log.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE action_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id    BIGINT,
    platform_code  VARCHAR(100),
    user_id        BIGINT,
    username       VARCHAR(255),
    menu_slug      VARCHAR(100),
    menu_path      TEXT,
    action         VARCHAR(50),
    request_method VARCHAR(10),
    request_url    TEXT,
    request_ip     VARCHAR(45),
    content        JSONB,
    created_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version        INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX action_logs_platform_id_idx   ON action_logs (platform_id);
CREATE INDEX action_logs_user_id_idx       ON action_logs (user_id);
CREATE INDEX action_logs_created_time_idx  ON action_logs (created_time DESC);
CREATE INDEX action_logs_menu_slug_idx     ON action_logs (menu_slug);
CREATE INDEX action_logs_content_gin_idx   ON action_logs USING GIN (content);
