-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS action_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    platform_id    BIGINT, -- 邏輯 FK → platforms(id)；方便列表依平台過濾
    menu_code      VARCHAR(100), -- 稽核快照，對應 menus.code（原 menu_slug）
    menu_path      TEXT,
    action         VARCHAR(50),
    request_method VARCHAR(10),
    request_url    TEXT,
    request_ip     VARCHAR(45),
    content        JSONB,
    created_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time   TIMESTAMPTZ,
    version        INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_al_ui         ON action_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_al_pi         ON action_logs (platform_id);
CREATE INDEX IF NOT EXISTS idx_al_ct         ON action_logs (created_time DESC);
CREATE INDEX IF NOT EXISTS idx_al_mc         ON action_logs (menu_code);
CREATE INDEX IF NOT EXISTS idx_al_c          ON action_logs USING GIN (content);
