-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS currencies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code_id BIGINT       NOT NULL UNIQUE, -- FK → currency_codes(id)
    name             VARCHAR(20)  NOT NULL,
    active           BOOLEAN      NOT NULL DEFAULT true,
    bet_options      JSONB        NOT NULL, -- 10 bet values ASC; app validates
    created_by       BIGINT,
    created_time     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time     TIMESTAMPTZ,
    version          INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_c_cci_n ON currencies (currency_code_id, name);
