-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_currency.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO public;

CREATE TABLE currencies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)       NOT NULL UNIQUE,
    status       VARCHAR(50)       NOT NULL DEFAULT 'active',
    cny_rate     DOUBLE PRECISION  NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_time TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);
