-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS games (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_code           VARCHAR(32)  NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    game_type           VARCHAR(50)  NOT NULL DEFAULT 'slot',
    active              BOOLEAN      NOT NULL DEFAULT false,
    has_ever_listed     BOOLEAN      NOT NULL DEFAULT false,
    supports_freegame   BOOLEAN      NOT NULL DEFAULT false,
    supports_bonusgame  BOOLEAN      NOT NULL DEFAULT false,
    exclusive_user_id   BIGINT,       -- FK → users(id)
    remark              TEXT,
    created_time        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time        TIMESTAMPTZ,
    version             INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_g_gt_a_gc ON games (game_type, active, game_code);
