-- Source: TP-5315 / game active status audit trail
-- 記錄 games.active 每次變更；應用層在更新 games.active 時同步寫入一筆。
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS game_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主鍵
    game_id         BIGINT      NOT NULL, -- FK → games(id)；哪個遊戲
    previous_active BOOLEAN     NOT NULL, -- 變更前狀態
    active          BOOLEAN     NOT NULL, -- 變更後狀態（與 games.active 一致）
    user_id         BIGINT,               -- FK → users(id)；操作者；migration backfill 可 NULL
    created_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- 事件時間
    updated_time    TIMESTAMPTZ,                       -- 最後更新時間；與專案其他表一致
    version         INTEGER     NOT NULL DEFAULT 0 -- 與專案其他表一致
);


-- 依遊戲 + 時間倒序（列表常用）
CREATE INDEX IF NOT EXISTS idx_gh_gi_ct ON game_history (game_id, created_time DESC);
-- 依遊戲查上架紀錄（active = true；含時間倒序）
CREATE INDEX IF NOT EXISTS idx_gh_gi_a_ct ON game_history (game_id, created_time DESC) WHERE active = true;
