-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE menus (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(50),
    parent_id    BIGINT, -- FK → menus(id)
    sort         INTEGER      NOT NULL DEFAULT 0,
    icon         VARCHAR(255),
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0
);
