-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_menu.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO public;

CREATE TABLE menus (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    slug         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(50),
    parent_id    BIGINT       REFERENCES menus(id),
    order_num    INTEGER      NOT NULL DEFAULT 0,
    icon         VARCHAR(255),
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);

CREATE TABLE menu_available_actions (
    menu_id BIGINT NOT NULL REFERENCES menus(id) ON DELETE CASCADE,
    action  VARCHAR(50) NOT NULL,
    PRIMARY KEY (menu_id, action)
);
