-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_permission.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO public;

CREATE TABLE permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    slug         VARCHAR(255) NOT NULL,
    menu_id      BIGINT       REFERENCES menus(id),
    action       VARCHAR(50)  NOT NULL,
    description  TEXT,
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);
