-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
--         + V3__permissions_role_type_mask.sql (merged — v1.0.0 baseline)
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    code            VARCHAR(255) NOT NULL UNIQUE,
    menu_id         BIGINT, -- FK → menus(id)
    action          VARCHAR(50)  NOT NULL,
    description     TEXT,
    role_type_mask  SMALLINT     NOT NULL DEFAULT 7,
    created_time    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time    TIMESTAMPTZ,
    version         INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT permissions_role_type_mask_chk
        CHECK (role_type_mask > 0 AND role_type_mask <= 7)
);

COMMENT ON COLUMN permissions.role_type_mask IS
    'Bitmask of roles.role_type that may be granted this permission. '
    'bit0=studio(1), bit1=master_agent(2), bit2=sub_account(4); e.g. 3=studio+master_agent.';
