-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS platform_api_test_runs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id  BIGINT      NOT NULL, -- FK → platforms(id), ON DELETE CASCADE
    callback_url VARCHAR(500), -- Callback URL under test for this run (TCG-147032 writes it)
    all_passed   BOOLEAN     NOT NULL, -- 5 步是否全過 (getSession -> GetBalance → Transfer DEBIT → Transfer CREDIT → TransferCancel)
    step_results JSONB       NOT NULL, -- 每一步通過與否、耗時、錯誤內容
    tested_by    BIGINT,     -- FK → users(id)
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_patr_pi_ct
    ON platform_api_test_runs (platform_id, created_time DESC);
