-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE platforms (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(100) NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL UNIQUE,
    owner_user_id      BIGINT       NOT NULL, -- FK → users(id)
    currency_id        BIGINT       NOT NULL, -- FK → currencies(id)
    wallet_type        VARCHAR(30)  NOT NULL DEFAULT 'single_wallet',
    compliance_enabled BOOLEAN      NOT NULL DEFAULT false,
    backend_visible    BOOLEAN      NOT NULL DEFAULT true,
    line_enabled       BOOLEAN      NOT NULL DEFAULT false,
    sequence_no        INTEGER      NOT NULL DEFAULT 1,
    active             BOOLEAN      NOT NULL DEFAULT true,
    created_time       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time       TIMESTAMPTZ,
    version            INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT platforms_wallet_type_chk CHECK (wallet_type IN ('single_wallet', 'transfer_wallet')),
    CONSTRAINT platforms_ma_currency_seq_key UNIQUE (owner_user_id, currency_id, sequence_no)
);

CREATE INDEX platforms_list_filter_idx ON platforms (owner_user_id, currency_id);
CREATE INDEX platforms_created_time_idx ON platforms (created_time);
CREATE INDEX platforms_currency_id_idx ON platforms (currency_id);
CREATE INDEX platforms_backend_visible_idx
    ON platforms (owner_user_id)
    WHERE backend_visible = true;

CREATE INDEX currencies_list_filter_idx ON currencies (currency_code_id, name);
