-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_platform.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO public;

CREATE TABLE platforms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)     NOT NULL,
    code          VARCHAR(100)     NOT NULL UNIQUE,
    domain_suffix VARCHAR(255),
    status        VARCHAR(50)      NOT NULL DEFAULT 'active',
    created_by    BIGINT,
    created_time  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_time  TIMESTAMPTZ
);
