-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE platforms (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(100) NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL UNIQUE,
    owner_user_id      BIGINT       NOT NULL, -- FK → users(id)
    currency_id        BIGINT       NOT NULL, -- FK → currencies(id)
    wallet_type        VARCHAR(30)  NOT NULL DEFAULT 'single_wallet',
    compliance_enabled BOOLEAN      NOT NULL DEFAULT false,
    backend_visible    BOOLEAN      NOT NULL DEFAULT true,
    line_enabled       BOOLEAN      NOT NULL DEFAULT false,
    sequence_no        INTEGER      NOT NULL DEFAULT 1,
    status             VARCHAR(50)  NOT NULL DEFAULT 'active',
    created_time       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time       TIMESTAMPTZ,
    version            INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT platforms_wallet_type_chk CHECK (wallet_type IN ('single_wallet', 'transfer_wallet')),
    CONSTRAINT platforms_ma_currency_seq_key UNIQUE (owner_user_id, currency_id, sequence_no)
);

CREATE INDEX platforms_list_filter_idx ON platforms (owner_user_id, currency_id);
CREATE INDEX platforms_created_time_idx ON platforms (created_time);
CREATE INDEX platforms_currency_id_idx ON platforms (currency_id);
CREATE INDEX platforms_backend_visible_idx
    ON platforms (owner_user_id)
    WHERE backend_visible = true;

CREATE TABLE platform_wallet_settings (
    platform_id  BIGINT       NOT NULL PRIMARY KEY, -- FK → platforms(id), ON DELETE CASCADE
    callback_url TEXT         NOT NULL UNIQUE,
    game_account VARCHAR(255) NOT NULL,
    timeout_secs INTEGER      NOT NULL DEFAULT 3,
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE platform_api_test_runs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id  BIGINT      NOT NULL, -- FK → platforms(id), ON DELETE CASCADE
    all_passed   BOOLEAN     NOT NULL,
    step_results JSONB       NOT NULL,
    tested_by    BIGINT,     -- FK → users(id)
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX platform_api_test_runs_platform_time_idx
    ON platform_api_test_runs (platform_id, created_time DESC);

CREATE INDEX currencies_list_filter_idx ON currencies (currency_code_id, name);
