-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE platform_api_test_runs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id  BIGINT      NOT NULL, -- FK → platforms(id), ON DELETE CASCADE
    all_passed   BOOLEAN     NOT NULL,
    step_results JSONB       NOT NULL,
    tested_by    BIGINT,     -- FK → users(id)
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER     NOT NULL DEFAULT 0
);

CREATE INDEX platform_api_test_runs_platform_time_idx
    ON platform_api_test_runs (platform_id, created_time DESC);
