-- SPM integration: RGS Edge callback URL registration (§1.3.2)
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS rgs_callback_subscription (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_type          VARCHAR(32)   NOT NULL,
    callback_base_url     VARCHAR(2048) NOT NULL,
    reported_host         VARCHAR(256),
    reported_port         INTEGER,
    reported_service_name VARCHAR(128),
    source                VARCHAR(64)   NOT NULL,
    reported_at           TIMESTAMPTZ,
    created_time          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_time          TIMESTAMPTZ,
    version               INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT uq_rgs_callback_subscription_service_type UNIQUE (service_type)
);
