-- Source: gs-gss-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    role_type    VARCHAR(50),
    protected    BOOLEAN      NOT NULL DEFAULT false,
    active       BOOLEAN      NOT NULL DEFAULT true,
    owner_user_id BIGINT,      -- FK → users(id)
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT roles_role_type_chk CHECK (role_type IN ('studio', 'master_agent', 'sub_account'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_r_rt_oui_n
    ON roles (role_type, owner_user_id, name)
    WHERE owner_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_r_rt_n
    ON roles (role_type, name)
    WHERE owner_user_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_r_rt_a_oui ON roles (role_type, active, owner_user_id);
