-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_role.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    role_type    VARCHAR(50),
    is_system    BOOLEAN      NOT NULL DEFAULT false,
    is_active    BOOLEAN      NOT NULL DEFAULT true,
    owner_id     BIGINT,
    created_by   BIGINT,
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);
