-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_tenant.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE tenants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    code         VARCHAR(100) NOT NULL,
    platform_id  BIGINT       REFERENCES platforms(id),
    currency_id  BIGINT       REFERENCES currencies(id),
    status       VARCHAR(50)  NOT NULL DEFAULT 'active',
    created_by   BIGINT,
    created_time TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0,
    UNIQUE (platform_id, code)
);
