-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/ddl/collections/gac_user.js
-- Source: gs-gss-server-21/src/main/resources/db/migration/V1__init.sql
SET search_path TO public;

CREATE TABLE users (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                   VARCHAR(255) NOT NULL,
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    nickname                   VARCHAR(255),
    user_type                  VARCHAR(50)  NOT NULL,
    platform_id                BIGINT       REFERENCES platforms(id),
    tenant_id                  BIGINT       REFERENCES tenants(id),
    parent_id                  BIGINT       REFERENCES users(id),
    owner_id                   BIGINT,
    created_by                 BIGINT,
    last_modified_by           BIGINT,
    is_system                  BOOLEAN      NOT NULL DEFAULT false,
    is_main_account            BOOLEAN      NOT NULL DEFAULT false,
    is_all_platform_accessible BOOLEAN      NOT NULL DEFAULT false,
    status                     VARCHAR(50)  NOT NULL DEFAULT 'active',
    status_reason              TEXT,
    last_login                 TIMESTAMPTZ,
    created_time               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time               TIMESTAMPTZ,
    version                    INTEGER      NOT NULL DEFAULT 0
);

-- Operator usernames are globally unique (platform_id IS NULL).
-- Agent/master-agent usernames are unique per platform.
CREATE UNIQUE INDEX users_username_operator_idx  ON users (username) WHERE platform_id IS NULL;
CREATE UNIQUE INDEX users_username_platform_idx  ON users (username, platform_id) WHERE platform_id IS NOT NULL;

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE user_accessible_platforms (
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platforms(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, platform_id)
);

CREATE TABLE user_suspensions (
    user_id        BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform_scope VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, platform_scope)
);
