-- Source: gs-gss-server-21/src/main/resources/db/migration/V2__init.sql
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS users (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                   VARCHAR(16)  NOT NULL UNIQUE,
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    nickname                   VARCHAR(50)  NOT NULL,
    user_type                  VARCHAR(50)  NOT NULL,
    agent_code                 VARCHAR(4),
    parent_id                  BIGINT, -- FK → users(id)
    last_modified_by           BIGINT,
    protected                  BOOLEAN      NOT NULL DEFAULT false,
    status                     VARCHAR(50)  NOT NULL DEFAULT 'active',
    last_login_time            TIMESTAMPTZ,
    last_login_ip              VARCHAR(45),
    created_time               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time               TIMESTAMPTZ,
    version                    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT users_user_type_chk CHECK (user_type IN ('studio', 'master_agent', 'sub_account'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_u_ac
    ON users (agent_code)
    WHERE user_type = 'master_agent' AND agent_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_u_pi ON users (parent_id);
CREATE INDEX IF NOT EXISTS idx_u_ut ON users (user_type);
CREATE INDEX IF NOT EXISTS idx_u_llt ON users (last_login_time);
CREATE INDEX IF NOT EXISTS idx_u_ut_pi_llt ON users (user_type, parent_id, last_login_time DESC);
