-- Source: ISO 4217 List One (Current Currency & Funds), Pblshd=2026-01-01
-- https://www.six-group.com/en/products-services/financial-information/data-standards.html
--
-- Note: list-three.xml is ISO List Three (historical / withdrawn currencies, HstrcCcyTbl).
--       currency_codes seeds active fiat only — from List One (<Ccy> alphabetic code).
--       178 unique codes (AED … ZWG); BGN withdrawn 2026-01 per Bulgaria euro adoption.
--
-- currencies: dev sample instances (USD01 / CNY01 / EUR01)
SET search_path TO gs_gss, public;

INSERT INTO currency_codes (id, code, type, created_time)
OVERRIDING SYSTEM VALUE
VALUES
    (  1, 'AED', 'fiat', NOW()),
    (  2, 'AFN', 'fiat', NOW()),
    (  3, 'ALL', 'fiat', NOW()),
    (  4, 'AMD', 'fiat', NOW()),
    (  5, 'AOA', 'fiat', NOW()),
    (  6, 'ARS', 'fiat', NOW()),
    (  7, 'AUD', 'fiat', NOW()),
    (  8, 'AWG', 'fiat', NOW()),
    (  9, 'AZN', 'fiat', NOW()),
    ( 10, 'BAM', 'fiat', NOW()),
    ( 11, 'BBD', 'fiat', NOW()),
    ( 12, 'BDT', 'fiat', NOW()),
    ( 13, 'BHD', 'fiat', NOW()),
    ( 14, 'BIF', 'fiat', NOW()),
    ( 15, 'BMD', 'fiat', NOW()),
    ( 16, 'BND', 'fiat', NOW()),
    ( 17, 'BOB', 'fiat', NOW()),
    ( 18, 'BOV', 'fiat', NOW()),
    ( 19, 'BRL', 'fiat', NOW()),
    ( 20, 'BSD', 'fiat', NOW()),
    ( 21, 'BTN', 'fiat', NOW()),
    ( 22, 'BWP', 'fiat', NOW()),
    ( 23, 'BYN', 'fiat', NOW()),
    ( 24, 'BZD', 'fiat', NOW()),
    ( 25, 'CAD', 'fiat', NOW()),
    ( 26, 'CDF', 'fiat', NOW()),
    ( 27, 'CHE', 'fiat', NOW()),
    ( 28, 'CHF', 'fiat', NOW()),
    ( 29, 'CHW', 'fiat', NOW()),
    ( 30, 'CLF', 'fiat', NOW()),
    ( 31, 'CLP', 'fiat', NOW()),
    ( 32, 'CNY', 'fiat', NOW()),
    ( 33, 'COP', 'fiat', NOW()),
    ( 34, 'COU', 'fiat', NOW()),
    ( 35, 'CRC', 'fiat', NOW()),
    ( 36, 'CUP', 'fiat', NOW()),
    ( 37, 'CVE', 'fiat', NOW()),
    ( 38, 'CZK', 'fiat', NOW()),
    ( 39, 'DJF', 'fiat', NOW()),
    ( 40, 'DKK', 'fiat', NOW()),
    ( 41, 'DOP', 'fiat', NOW()),
    ( 42, 'DZD', 'fiat', NOW()),
    ( 43, 'EGP', 'fiat', NOW()),
    ( 44, 'ERN', 'fiat', NOW()),
    ( 45, 'ETB', 'fiat', NOW()),
    ( 46, 'EUR', 'fiat', NOW()),
    ( 47, 'FJD', 'fiat', NOW()),
    ( 48, 'FKP', 'fiat', NOW()),
    ( 49, 'GBP', 'fiat', NOW()),
    ( 50, 'GEL', 'fiat', NOW()),
    ( 51, 'GHS', 'fiat', NOW()),
    ( 52, 'GIP', 'fiat', NOW()),
    ( 53, 'GMD', 'fiat', NOW()),
    ( 54, 'GNF', 'fiat', NOW()),
    ( 55, 'GTQ', 'fiat', NOW()),
    ( 56, 'GYD', 'fiat', NOW()),
    ( 57, 'HKD', 'fiat', NOW()),
    ( 58, 'HNL', 'fiat', NOW()),
    ( 59, 'HTG', 'fiat', NOW()),
    ( 60, 'HUF', 'fiat', NOW()),
    ( 61, 'IDR', 'fiat', NOW()),
    ( 62, 'ILS', 'fiat', NOW()),
    ( 63, 'INR', 'fiat', NOW()),
    ( 64, 'IQD', 'fiat', NOW()),
    ( 65, 'IRR', 'fiat', NOW()),
    ( 66, 'ISK', 'fiat', NOW()),
    ( 67, 'JMD', 'fiat', NOW()),
    ( 68, 'JOD', 'fiat', NOW()),
    ( 69, 'JPY', 'fiat', NOW()),
    ( 70, 'KES', 'fiat', NOW()),
    ( 71, 'KGS', 'fiat', NOW()),
    ( 72, 'KHR', 'fiat', NOW()),
    ( 73, 'KMF', 'fiat', NOW()),
    ( 74, 'KPW', 'fiat', NOW()),
    ( 75, 'KRW', 'fiat', NOW()),
    ( 76, 'KWD', 'fiat', NOW()),
    ( 77, 'KYD', 'fiat', NOW()),
    ( 78, 'KZT', 'fiat', NOW()),
    ( 79, 'LAK', 'fiat', NOW()),
    ( 80, 'LBP', 'fiat', NOW()),
    ( 81, 'LKR', 'fiat', NOW()),
    ( 82, 'LRD', 'fiat', NOW()),
    ( 83, 'LSL', 'fiat', NOW()),
    ( 84, 'LYD', 'fiat', NOW()),
    ( 85, 'MAD', 'fiat', NOW()),
    ( 86, 'MDL', 'fiat', NOW()),
    ( 87, 'MGA', 'fiat', NOW()),
    ( 88, 'MKD', 'fiat', NOW()),
    ( 89, 'MMK', 'fiat', NOW()),
    ( 90, 'MNT', 'fiat', NOW()),
    ( 91, 'MOP', 'fiat', NOW()),
    ( 92, 'MRU', 'fiat', NOW()),
    ( 93, 'MUR', 'fiat', NOW()),
    ( 94, 'MVR', 'fiat', NOW()),
    ( 95, 'MWK', 'fiat', NOW()),
    ( 96, 'MXN', 'fiat', NOW()),
    ( 97, 'MXV', 'fiat', NOW()),
    ( 98, 'MYR', 'fiat', NOW()),
    ( 99, 'MZN', 'fiat', NOW()),
    (100, 'NAD', 'fiat', NOW()),
    (101, 'NGN', 'fiat', NOW()),
    (102, 'NIO', 'fiat', NOW()),
    (103, 'NOK', 'fiat', NOW()),
    (104, 'NPR', 'fiat', NOW()),
    (105, 'NZD', 'fiat', NOW()),
    (106, 'OMR', 'fiat', NOW()),
    (107, 'PAB', 'fiat', NOW()),
    (108, 'PEN', 'fiat', NOW()),
    (109, 'PGK', 'fiat', NOW()),
    (110, 'PHP', 'fiat', NOW()),
    (111, 'PKR', 'fiat', NOW()),
    (112, 'PLN', 'fiat', NOW()),
    (113, 'PYG', 'fiat', NOW()),
    (114, 'QAR', 'fiat', NOW()),
    (115, 'RON', 'fiat', NOW()),
    (116, 'RSD', 'fiat', NOW()),
    (117, 'RUB', 'fiat', NOW()),
    (118, 'RWF', 'fiat', NOW()),
    (119, 'SAR', 'fiat', NOW()),
    (120, 'SBD', 'fiat', NOW()),
    (121, 'SCR', 'fiat', NOW()),
    (122, 'SDG', 'fiat', NOW()),
    (123, 'SEK', 'fiat', NOW()),
    (124, 'SGD', 'fiat', NOW()),
    (125, 'SHP', 'fiat', NOW()),
    (126, 'SLE', 'fiat', NOW()),
    (127, 'SOS', 'fiat', NOW()),
    (128, 'SRD', 'fiat', NOW()),
    (129, 'SSP', 'fiat', NOW()),
    (130, 'STN', 'fiat', NOW()),
    (131, 'SVC', 'fiat', NOW()),
    (132, 'SYP', 'fiat', NOW()),
    (133, 'SZL', 'fiat', NOW()),
    (134, 'THB', 'fiat', NOW()),
    (135, 'TJS', 'fiat', NOW()),
    (136, 'TMT', 'fiat', NOW()),
    (137, 'TND', 'fiat', NOW()),
    (138, 'TOP', 'fiat', NOW()),
    (139, 'TRY', 'fiat', NOW()),
    (140, 'TTD', 'fiat', NOW()),
    (141, 'TWD', 'fiat', NOW()),
    (142, 'TZS', 'fiat', NOW()),
    (143, 'UAH', 'fiat', NOW()),
    (144, 'UGX', 'fiat', NOW()),
    (145, 'USD', 'fiat', NOW()),
    (146, 'USN', 'fiat', NOW()),
    (147, 'UYI', 'fiat', NOW()),
    (148, 'UYU', 'fiat', NOW()),
    (149, 'UYW', 'fiat', NOW()),
    (150, 'UZS', 'fiat', NOW()),
    (151, 'VED', 'fiat', NOW()),
    (152, 'VES', 'fiat', NOW()),
    (153, 'VND', 'fiat', NOW()),
    (154, 'VUV', 'fiat', NOW()),
    (155, 'WST', 'fiat', NOW()),
    (156, 'XAD', 'fiat', NOW()),
    (157, 'XAF', 'fiat', NOW()),
    (158, 'XAG', 'fiat', NOW()),
    (159, 'XAU', 'fiat', NOW()),
    (160, 'XBA', 'fiat', NOW()),
    (161, 'XBB', 'fiat', NOW()),
    (162, 'XBC', 'fiat', NOW()),
    (163, 'XBD', 'fiat', NOW()),
    (164, 'XCD', 'fiat', NOW()),
    (165, 'XCG', 'fiat', NOW()),
    (166, 'XDR', 'fiat', NOW()),
    (167, 'XOF', 'fiat', NOW()),
    (168, 'XPD', 'fiat', NOW()),
    (169, 'XPF', 'fiat', NOW()),
    (170, 'XPT', 'fiat', NOW()),
    (171, 'XSU', 'fiat', NOW()),
    (172, 'XTS', 'fiat', NOW()),
    (173, 'XUA', 'fiat', NOW()),
    (174, 'XXX', 'fiat', NOW()),
    (175, 'YER', 'fiat', NOW()),
    (176, 'ZAR', 'fiat', NOW()),
    (177, 'ZMW', 'fiat', NOW()),
    (178, 'ZWG', 'fiat', NOW()),
    (179, 'TLB', 'fiat', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO currencies (id, currency_code_id, code, name, currency_type, active, bet_options, created_by, created_time)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 145, 'USD01', '美元', 'fiat', true, '[0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100]'::jsonb, 0, NOW()),
    (2, 32, 'CNY01', '人民幣', 'fiat', true, '[1, 2, 5, 10, 20, 50, 100, 200, 500, 1000]'::jsonb, 0, NOW()),
    (3, 46, 'EUR01', '歐元', 'fiat', true, '[0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100]'::jsonb, 0, NOW()),
    (4, 179, 'TLB01', '披索', 'fiat', true, '[0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100]'::jsonb, 0, NOW())
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('currency_codes', 'id'), (SELECT COALESCE(MAX(id), 1) FROM currency_codes));
SELECT setval(pg_get_serial_sequence('currencies', 'id'), (SELECT COALESCE(MAX(id), 1) FROM currencies));