-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/seed/menu-seed.js
-- Source: gs-gss-server-21/src/main/resources/db/dev-seed/V2__dev_seed.sql
SET search_path TO public;

INSERT INTO menus (id, name, slug, type, parent_id, order_num, icon, created_time)
OVERRIDING SYSTEM VALUE
VALUES
    (1, '系統管理', 'system', 'category', NULL, 1, 'setting', NOW()),
    (2, '後台管理', 'backend', 'category', NULL, 2, 'team', NOW()),
    (3, '帳號管理', 'account', 'category', NULL, 3, 'user', NOW()),
    (4, '遊戲管理', 'game', 'category', NULL, 4, 'appstore', NOW()),
    (5, '公告管理', 'announcement', 'category', NULL, 5, 'notification', NOW()),
    (6, '營運管理', 'operation', 'category', NULL, 6, 'bar-chart', NOW());

INSERT INTO menus (id, name, slug, type, parent_id, order_num, created_time)
OVERRIDING SYSTEM VALUE
VALUES
    (7, '貨幣管理', 'currency', 'page', 1, 1, NOW()),
    (8, '平台管理', 'platform', 'page', 1, 2, NOW()),
    (9, '角色管理', 'role', 'page', 1, 3, NOW()),
    (10, '系統用戶管理', 'operator', 'page', 1, 4, NOW()),
    (11, '系統用戶日誌', 'action_log', 'page', 1, 5, NOW()),
    (12, '線路遊戲模板', 'game_template', 'page', 1, 6, NOW()),
    (13, '遊戲開關設置', 'game_switch', 'page', 1, 7, NOW()),
    (14, '總代理管理', 'master_agent', 'page', 2, 1, NOW()),
    (15, '代理管理', 'agent', 'page', 2, 2, NOW()),
    (16, '線路遊戲配置', 'game_setting', 'page', 2, 3, NOW()),
    (17, '重置遊戲RTP', 'rtp_reset', 'page', 2, 4, NOW()),
    (18, '線路RTP數據', 'rtp_data', 'page', 2, 5, NOW()),
    (19, '線路管理', 'tenant', 'page', 2, 6, NOW()),
    (20, '代理用戶', 'user', 'page', 2, 7, NOW()),
    (21, '代理管理 todo', 'my_agent', 'page', 3, 1, NOW()),
    (22, '子帳號管理', 'sub_account', 'page', 3, 2, NOW()),
    (23, '角色設定 todo', 'my_role', 'page', 3, 3, NOW()),
    (24, '玩家管理 todo', 'player', 'page', 3, 4, NOW()),
    (25, '遊戲列表 todo', 'game_list', 'page', 4, 1, NOW()),
    (26, '跑馬燈設置 todo', 'marquee', 'page', 5, 1, NOW()),
    (27, '投注紀錄', 'order', 'page', 6, 1, NOW()),
    (28, '遊戲局紀錄 todo', 'round', 'page', 6, 2, NOW()),
    (29, '白名單管理 todo', 'whitelist', 'page', 6, 3, NOW()),
    (30, '資料下載 todo', 'download', 'page', 6, 4, NOW());

INSERT INTO menu_available_actions (menu_id, action) VALUES
    (7, 'view'),
    (7, 'create'),
    (7, 'edit'),
    (8, 'view'),
    (8, 'create'),
    (8, 'edit'),
    (9, 'view'),
    (9, 'create'),
    (9, 'edit'),
    (9, 'delete'),
    (10, 'view'),
    (10, 'create'),
    (10, 'edit'),
    (10, 'delete'),
    (10, 'reset_password'),
    (11, 'view'),
    (12, 'view'),
    (12, 'create'),
    (12, 'edit'),
    (12, 'delete'),
    (13, 'view'),
    (13, 'edit'),
    (14, 'view'),
    (14, 'create'),
    (14, 'edit'),
    (15, 'view'),
    (15, 'create'),
    (15, 'edit'),
    (16, 'view'),
    (16, 'create'),
    (16, 'edit'),
    (16, 'delete'),
    (16, 'import'),
    (17, 'edit'),
    (18, 'view'),
    (19, 'view'),
    (20, 'view'),
    (21, 'view'),
    (22, 'view'),
    (22, 'create'),
    (22, 'edit'),
    (22, 'delete'),
    (23, 'view'),
    (24, 'view'),
    (25, 'view'),
    (26, 'view'),
    (26, 'create'),
    (26, 'edit'),
    (26, 'delete'),
    (27, 'view'),
    (27, 'edit'),
    (27, 'detail'),
    (27, 'export'),
    (28, 'view'),
    (29, 'view'),
    (29, 'create'),
    (29, 'edit'),
    (29, 'delete'),
    (30, 'view');
