-- Mirror: gac-mongo-patch scripts/v1.0.0/TP-0000/seed/permission-seed.js
-- Source: gs-gss-server-21/src/main/resources/db/dev-seed/V2__dev_seed.sql
SET search_path TO public;

INSERT INTO permissions (id, name, slug, menu_id, action, description, created_time)
OVERRIDING SYSTEM VALUE
VALUES
    (1, '貨幣管理 - 查看', 'currency:view', 7, 'view', '查看貨幣列表', NOW()),
    (2, '貨幣管理 - 新增', 'currency:create', 7, 'create', '新增貨幣', NOW()),
    (3, '貨幣管理 - 更新', 'currency:edit', 7, 'edit', '更新或停用貨幣', NOW()),
    (4, '平台管理 - 查看', 'platform:view', 8, 'view', '查看平台列表', NOW()),
    (5, '平台管理 - 新增', 'platform:create', 8, 'create', '新增平台', NOW()),
    (6, '平台管理 - 更新', 'platform:edit', 8, 'edit', '更新或停用平台', NOW()),
    (7, '角色管理 - 新增', 'role:create', 9, 'create', '建立角色', NOW()),
    (8, '角色管理 - 更新', 'role:edit', 9, 'edit', '編輯角色內容與配置', NOW()),
    (9, '角色管理 - 刪除', 'role:delete', 9, 'delete', '刪除角色', NOW()),
    (10, '角色管理 - 查看', 'role:view', 9, 'view', '查看角色列表', NOW()),
    (11, '系統用戶管理 - 查看', 'operator:view', 10, 'view', '查看營運帳號列表', NOW()),
    (12, '系統用戶管理 - 新增', 'operator:create', 10, 'create', '建立營運帳號', NOW()),
    (13, '系統用戶管理 - 更新', 'operator:edit', 10, 'edit', '更新營運帳號', NOW()),
    (14, '系統用戶管理 - 刪除', 'operator:delete', 10, 'delete', '刪除營運帳號', NOW()),
    (15, '系統用戶管理 - 重設密碼', 'operator:reset_password', 10, 'reset_password', '重設營運帳號密碼', NOW()),
    (16, '系統用戶日誌 - 查看', 'action_log:view', 11, 'view', '查詢用戶異動紀錄', NOW()),
    (17, '線路遊戲模板 - 查看', 'game_template:view', 12, 'view', '查看遊戲模板列表', NOW()),
    (18, '線路遊戲模板 - 新增', 'game_template:create', 12, 'create', '建立遊戲模板（幣別與遊戲設定）', NOW()),
    (19, '線路遊戲模板 - 更新', 'game_template:edit', 12, 'edit', '更新遊戲模板設定', NOW()),
    (20, '線路遊戲模板 - 刪除', 'game_template:delete', 12, 'delete', '刪除遊戲模板', NOW()),
    (21, '遊戲開關設置 - 查看', 'game_switch:view', 13, 'view', '查看遊戲開關狀態', NOW()),
    (22, '遊戲開關設置 - 更新', 'game_switch:edit', 13, 'edit', '設定系統遊戲開關', NOW()),
    (23, '總代理管理 - 查看', 'master_agent:view', 14, 'view', '查看總代理列表', NOW()),
    (24, '總代理管理 - 新增', 'master_agent:create', 14, 'create', '建立總代理帳號', NOW()),
    (25, '總代理管理 - 更新', 'master_agent:edit', 14, 'edit', '更新總代理資料與設定', NOW()),
    (26, '總代理管理 - 稽核', 'master_agent:audit', 14, 'audit', '稽核/刪除總代理帳號', NOW()),
    (27, '代理管理 - 查看', 'agent:view', 15, 'view', '查看代理列表與表單選項', NOW()),
    (28, '代理管理 - 新增', 'agent:create', 15, 'create', '建立代理帳號', NOW()),
    (29, '代理管理 - 更新', 'agent:edit', 15, 'edit', '更新代理資料（所屬總代、幣別、錢包）', NOW()),
    (30, '代理用戶 - 查看', 'user:view', 20, 'view', '查看代理帳號列表（後台代理用戶）', NOW()),
    (31, '線路管理 - 查看', 'tenant:view', 19, 'view', '查看線路（Tenant）列表', NOW()),
    (32, '線路遊戲配置 - 查看', 'game_setting:view', 16, 'view', '查看線路遊戲配置', NOW()),
    (33, '線路遊戲配置 - 新增', 'game_setting:create', 16, 'create', '建立線路遊戲配置', NOW()),
    (34, '線路遊戲配置 - 更新', 'game_setting:edit', 16, 'edit', '更新線路遊戲配置', NOW()),
    (35, '線路遊戲配置 - 刪除', 'game_setting:delete', 16, 'delete', '刪除遊戲配置', NOW()),
    (36, '線路遊戲配置 - 匯入', 'game_setting:import', 16, 'import', '匯入線路遊戲配置', NOW()),
    (37, '重置遊戲RTP - 更新', 'rtp_reset:edit', 17, 'edit', '設定重置遊戲累計金額', NOW()),
    (38, '線路RTP數據 - 查看', 'rtp_data:view', 18, 'view', '查看線路當前RTP狀態與重置紀錄', NOW()),
    (39, '代理帳號管理 - 查看', 'my_agent:view', 21, 'view', '查看代理帳號資料', NOW()),
    (40, '子帳號管理 - 查看', 'sub_account:view', 22, 'view', '查看子帳號列表', NOW()),
    (41, '子帳號管理 - 新增', 'sub_account:create', 22, 'create', '建立子帳號', NOW()),
    (42, '子帳號管理 - 更新', 'sub_account:edit', 22, 'edit', '更新子帳號設定', NOW()),
    (43, '子帳號管理 - 刪除', 'sub_account:delete', 22, 'delete', '刪除子帳號', NOW()),
    (44, '我的角色管理 - 查看', 'my_role:view', 23, 'view', '查看角色列表（帳號管理範圍）', NOW()),
    (45, '玩家管理 - 查看', 'player:view', 24, 'view', '查詢玩家資訊', NOW()),
    (46, '遊戲列表 - 查看', 'game_list:view', 25, 'view', '查看遊戲列表（含營收或當前RTP）', NOW()),
    (47, '跑馬燈設置 - 查看', 'marquee:view', 26, 'view', '查看跑馬燈設置', NOW()),
    (48, '跑馬燈設置 - 新增', 'marquee:create', 26, 'create', '新增跑馬燈', NOW()),
    (49, '跑馬燈設置 - 更新', 'marquee:edit', 26, 'edit', '更新跑馬燈設定', NOW()),
    (50, '跑馬燈設置 - 刪除', 'marquee:delete', 26, 'delete', '刪除跑馬燈', NOW()),
    (51, '投注紀錄 - 查看', 'order:view', 27, 'view', '查看遊戲數據歷程', NOW()),
    (52, '投注紀錄 - 詳情', 'order:detail', 27, 'detail', '查閱單筆投注訂單詳情', NOW()),
    (53, '投注紀錄 - 編輯', 'order:edit', 27, 'edit', '編輯投注紀錄', NOW()),
    (54, '投注紀錄 - 導出', 'order:export', 27, 'export', '導出投注紀錄', NOW()),
    (55, '遊戲局紀錄 - 查看', 'round:view', 28, 'view', '以局為單位查看單局遊戲紀錄', NOW()),
    (56, '白名單管理 - 查看', 'whitelist:view', 29, 'view', '查看各角色可登入白名單', NOW()),
    (57, '白名單管理 - 新增', 'whitelist:create', 29, 'create', '新增白名單', NOW()),
    (58, '白名單管理 - 更新', 'whitelist:edit', 29, 'edit', '更新白名單', NOW()),
    (59, '白名單管理 - 刪除', 'whitelist:delete', 29, 'delete', '刪除白名單', NOW()),
    (60, '資料下載 - 查看', 'download:view', 30, 'view', '顯示對接相關資訊', NOW());
