-- TCG-158901: DB-driven purge framework — setting table (which tables to purge)
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS purge_data_setting (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name             VARCHAR(128) NOT NULL,
    purge_sequence         INTEGER      NOT NULL,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    retain_days            SMALLINT     NOT NULL,
    date_field             VARCHAR(64)  NOT NULL,
    batch_size             INTEGER      NOT NULL,
    max_batches            INTEGER      NOT NULL,
    max_execution_seconds  INTEGER      NOT NULL,
    continue_on_error      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_time           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time           TIMESTAMPTZ,
    version                INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_pds_table_name UNIQUE (table_name),
    CONSTRAINT ck_pds_retain_days CHECK (retain_days > 0),
    CONSTRAINT ck_pds_batch_size CHECK (batch_size > 0),
    CONSTRAINT ck_pds_max_batches CHECK (max_batches > 0),
    CONSTRAINT ck_pds_max_execution_seconds CHECK (max_execution_seconds > 0)
);
