-- TCG-158901: DB-driven purge framework — job/table execution summaries
SET search_path TO gs_gss, public;

CREATE TABLE IF NOT EXISTS purge_data_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            UUID         NOT NULL,
    record_type       VARCHAR(16)  NOT NULL,
    scope_key         VARCHAR(160) NOT NULL,
    job_name          VARCHAR(128) NOT NULL,
    setting_id        BIGINT,
    table_name        VARCHAR(128),
    status            VARCHAR(16)  NOT NULL,
    retain_days       SMALLINT,
    date_field        VARCHAR(64),
    cutoff_time       TIMESTAMPTZ,
    deleted_row_count BIGINT       NOT NULL DEFAULT 0,
    batch_count       INTEGER      NOT NULL DEFAULT 0,
    started_time      TIMESTAMPTZ  NOT NULL,
    finished_time     TIMESTAMPTZ,
    elapsed_ms        BIGINT,
    remark            TEXT,
    error_message     TEXT,
    created_time      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_time      TIMESTAMPTZ,
    version           INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_pdl_run_scope UNIQUE (run_id, scope_key),
    CONSTRAINT ck_pdl_record_type CHECK (record_type IN ('JOB', 'TABLE')),
    CONSTRAINT ck_pdl_status CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', 'DRY_RUN'))
);

CREATE INDEX IF NOT EXISTS idx_pdl_started
    ON purge_data_log (started_time DESC);

CREATE INDEX IF NOT EXISTS idx_pdl_status_started
    ON purge_data_log (status, started_time DESC);

CREATE INDEX IF NOT EXISTS idx_pdl_table_started
    ON purge_data_log (table_name, started_time DESC);
