-- TCG-165041: 初始遊戲支援語系——CN/EN 沿用系統既有慣用兩碼排最前，
-- 其餘 36 種依 Jira 規格公布的支援語系清單續接（含 UR-LA、PT-BR 等連字號代碼）
SET search_path TO gs_gss, public;

INSERT INTO game_supported_languages (code, sort_order) VALUES
    ('CN', 1),
    ('EN', 2),
    ('HI', 3),
    ('DE', 4),
    ('TW', 5),
    ('RU', 6),
    ('LO', 7),
    ('PT', 8),
    ('TY', 9),
    ('HN', 10),
    ('FR', 11),
    ('BN', 12),
    ('ID', 13),
    ('UR', 14),
    ('KM', 15),
    ('KO', 16),
    ('SW', 17),
    ('MR', 18),
    ('MS', 19),
    ('IT', 20),
    ('MY', 21),
    ('TA', 22),
    ('GT', 23),
    ('ES', 24),
    ('TE', 25),
    ('AR', 26),
    ('VI', 27),
    ('TH', 28),
    ('UR-LA', 29),
    ('JA', 30),
    ('PT-BR', 31),
    ('NE', 32),
    ('HA', 33),
    ('NI', 34),
    ('FA', 35),
    ('PL', 36),
    ('NL', 37),
    ('TR', 38)
ON CONFLICT (code) DO NOTHING;
